project_id = "abcojhdnhxatbmdmyiav"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[functions.share-pulse-results]
verify_jwt = false

[functions.get-shared-results]
verify_jwt = false