// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abcojhdnhxatbmdmyiav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiY29qaGRuaHhhdGJtZG15aWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTc2MTMsImV4cCI6MjA2NTk5MzYxM30.jXQKp9-cjD-7uLgYokhfT4u2UpStkL8_9uSdVooTN-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);